spring:
  application:
    name: x-clone-backend

  # GraphQL Configuration
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
    schema:
      printer:
        enabled: true
    path: /graphql
    websocket:
      path: /graphql-ws

# JWT Configuration (you'll add this later)
jwt:
  secret: ${JWT_SECRET:DLAFZBVVg4tKQcYcM5MqPZjasrFBVUnk}
  algorithm: HS256
  issuer: x-clone

# Logging
logging:
  level:
    com.xclone: DEBUG
    org.springframework.graphql: DEBUG
    org.springframework.security: DEBUG

app:
  auth:
    access-token-duration-seconds: 900 # 15 mins
    refresh-token-duration-seconds: 2592000 # 30 days
    secure-cookies: true